<datalist id="departments">
    <option value="ກອງພົນທີ 1"></option>
    <option value="ກອງພົນທີ 2"></option>
    <option value="ກອງພົນທີ 3"></option>
    <option value="ກອງພົນທີ 4"></option>
    <option value="ກອງພົນທີ່ 5"></option>
    <option value="ກົມ 213"></option>
    <option value="ກົມວິທະຍາສາດປະຫວັດສາດ"></option>
    <option value="ກອງບັນຊາການທະຫານອາກາດ"></option>
    <option value="ໂຮງຮຽນທິດສະດີການເມືອງ"></option>
    <option value="ທະຫານແຂວງ ນະຄອນຫຼວງ"></option>
    <option value="ທະຫານແຂວງ ວຽງຈັນ"></option>
    <option value="ທະຫານແຂວງ ສະຫວັນນະເຂດ"></option>
    <option value="ທະຫານແຂວງ ຫຼວງພະບາງ"></option>
    <option value="ທະຫານແຂວງ ຈຳປາສັກ"></option>
    <option value="ທະຫານແຂວງ ບໍລິຄຳໄຊ"></option>
    <option value="ທະຫານແຂວງ ສາລະວັນ"></option>
    <option value="ທະຫານແຂວງ ອັດຕະປື"></option>
    <option value="ທະຫານແຂວງ ເຊກອງ"></option>
    <option value="ທະຫານແຂວງ ຄຳມ່ວນ"></option>
    <option value="ທະຫານແຂວງ ຊຽງຂວາງ"></option>
    <option value="ທະຫານແຂວງ ອຸດົມໄຊ"></option>
    <option value="ທະຫານແຂວງ ຫຼວງນ້ຳທາ"></option>
    <option value="ທະຫານແຂວງ ບໍ່ແກ້ວ"></option>
    <option value="ທະຫານແຂວງ ຫົວພັນ"></option>
    <option value="ທະຫານແຂວງ ຜົ້ງສາລີ"></option>
    <option value="ທະຫານແຂວງ ໄຊຍະບູລີ"></option>
    <option value="ທະຫານແຂວງ ໄຊສົມບູນ"></option>
    <option value="ວິທະຍາຄານ ໄກສອນ ພົມວິຫານ"></option>
    <option value="ວິທະຍາຄານ ພະລາທິການກອງທັບ"></option>
    <option value="ວິທະຍາຄານ ກົມມະດຳ"></option>
    <option value="ວິທະຍາຄານ ເຕັກນິກການທະຫານ"></option>
    <option value="ໂຮງຮຽນ ນາຍສິບເລກ 1"></option>
    <option value="ໂຮງຮຽນ ນາຍສິບເລກ 2"></option>
    <option value="ວິທະຍາຄານ ການແພດກອງທັບ"></option>
    <option value="ໂຮງຮຽນ 303"></option>
    <option value="ໂຮງຮຽນ 307"></option>
    <option value="ໂຮງຮຽນ 301"></option>
    <option value="ໂຮງຮຽນ 306"></option>
    <option value="ໂຮງຮຽນ 205"></option>
    <option value="ໂຮງຮຽນ 404"></option>
    <option value="ໂຮງໝໍ 103"></option>
    <option value="ໂຮງໝໍ 106"></option>
    <option value="ໂຮງໝໍ 109"></option>
    <option value="ໂຮງໝໍ 101"></option>
    <option value="ໂຮງໝໍ 107"></option>
    <option value="ໂຮງຮຽນ 712 ຊາຍແດນ"></option>
    <option value="ໂຮງງານ ປະສານເຫຼົ່າຫຼວງພະບາງ"></option>
    <option value="ກອງພັນໃຫຍ່ 11"></option>
    <option value="ກອງພັນໃຫຍ່ 279"></option>
    <option value="ກອງພັນໃຫຍ່ 605"></option>
    <option value="ກອງພັນໃຫຍ່ 641"></option>
    <option value="ກອງພັນໃຫຍ່ 661"></option>
    <option value="ກອງພັນໃຫຍ່ 703"></option>
    <option value="ກອງພັນໃຫຍ່ 497"></option>
    <option value="ກອງພັນໃຫຍ່ 584"></option>
    <option value="ກອງພັນໃຫຍ່ 642"></option>
    <option value="ກອງພັນໃຫຍ່ 643"></option>
    <option value="ກອງພັນໃຫຍ່ 644"></option>
    <option value="ກອງພັນໃຫຍ່ 645"></option>
    <option value="ກອງພັນໃຫຍ່ 702"></option>
    <option value="ກອງພັນໃຫ່ຍ 621"></option>
    <option value="ກອງພັນ 233"></option>
    <option value="ກອງພັນ 1.60"></option>
    <option value="ກອງພັນໃຫຍ່ 941 (ປ່າສະຫງວນ)"></option>
    <option value="ໂຮງຮຽນ712 (ທະຫານຊາຍແດນ)"></option>
    <option value="ກົມໃຫຍ່ເຕັກນິກ ກອງທັບ"></option>
    <option value="ກົມຄຸ້ມຄອງລົດ"></option>
    <option value="ກົມອຸດສາຫະກຳ"></option>
    <option value="ກົມຄຸ້ມຄອງອາວຸດກະສູນ"></option>
    <option value="ສະຖາບັນກັນພະຍາດ 108"></option>
    <option value="ກົມໃຫຍ່ພະລາທິການ"></option>
    <option value="ຫ້ອງການກົມໃຫຍ່ພະລາ"></option>
    <option value="ກົມແຜນການ-ການເງິນ"></option>
    <option value="ກົມອຸປະໂພກ-ບໍລິໂພກ"></option>
    <option value="ລັດວິສາຫະກິດການຄ້າ"></option>
    <option value="ສາງອຸປະໂພກ-ບໍລິໂພກ"></option>
    <option value="ໂຮງງານຕັດຫຍິບເລກ 1 ກອງທັບ"></option>
    <option value="ບໍລິສັດ 20 ມັງກອນ"></option>
    <option value="ກົມນ້ຳມັນເຊື້ອໄຟ"></option>
    <option value="ບໍລິສັດນ້ຳມັນເຊື້ອໄຟວຽງຈັນ"></option>
    <option value="ກົມເສນາຮັກ"></option>
    <option value="ກົມກໍ່ສ້າງ"></option>
    <option value="ກົມຜະລິດກະສິກຳ"></option>
    <option value="ກຸ່ມຜະລິດເລກ1"></option>
    <option value="ກອງຜະລິດເລກ2"></option>
    <option value="ກອງສາລາປານ້ຳຫຸມ"></option>
    <option value="ກົມຂົນສົ່ງ"></option>
    <option value="ກົມເສນາພະລາ"></option>
    <option value="ສາງຢາເລກ 2"></option>
    <option value="ບໍລິສັດຕ່ຳແຜນຍອມສີ ລາວ-ຫວຽດນາມ"></option>
    <option value="ຫ້ອງການເມືອງ"></option>
    <option value="ຫ້ອງບໍລິຫານ"></option>
    <option value="ກົມໃຫຍ່ເສນາທິການ"></option>
    <option value="ກົມສູ້ຮົບ"></option>
    <option value="ກົມສື່ສານ"></option>
    <option value="ກົມຊ່າງແສງ"></option>
    <option value="ກົມອົບຮົມ"></option>
    <option value="ກົມຊາຍແດນ"></option>
    <option value="ກົມແຜນທີ່"></option>
    <option value="ກົມຈັດຕັ້ງລະດົມພົນ"></option>
    <option value="ກົມ 49"></option>
    <option value="ກົມເຄມີ"></option>
    <option value="ກົມປ້ອງກັນອາກາດ"></option>
    <option value="ກົມປືນໃຫຍ່"></option>
    <option value="ກົມລົດຕັງ"></option>
    <option value="ກົມໃຫຍ່ການເມືອງ ກອງທັບ"></option>
    <option value="ສານທະຫານຂັ້ນສູງ"></option>
    <option value="ກົມກວດກາກອງທັບ"></option>
    <option value="ກົມໄວຍະການ"></option>
    <option value="ກົມສານທະຫານ"></option>
    <option value="ຫ້ອງວ່າການກະຊວງ"></option>
    <option value="ກຸ່ມບໍລິສັດ ພັດທະນາຊົນນະບົດໃໝ່"></option>
    <option value="ໂຮງສີເຂົ້າໜອງແຕ່ງ"></option>
    <option value="ກອງພັນ 174 ລົດຕັງ"></option>
    <option value="ກອງພັນ 425"></option>
    <option value="ໂຮງຮຽນຊ່າງແສງ"></option>
    <option value="ກອງພັນ433"></option>
    <option value="ໂຮງງານເກີບທັນວາ"></option>
    <option value="ກອງຍິງປືນອາຊຽນ"></option>
    <option value="ບໍລິສັດກໍ່ສ້າງ-ຂົວທາງຄົບວົງຈອນ"></option>
    <option value="ກົມກົດລັບ"></option>
    <option value="ຫ້ອງການກົມໃຫຍ່ພະລາ"></option>
    <option value="ຄັງວຽງພາກສະໜາມ"></option>
    <option value="ກອງພັນ 401"></option>
    <option value="ກອງພັນ 402"></option>
    <option value="ສະຖາບັນການຢາ-ການແພດພື້ນເມືອງກອງທັບ"></option>
    <option value="ໂຮງຮຽນຊ່າງແສງ"></option>
    <option value="ສູນ 489"></option>
    <option value="ໂຮງຮຽນ 303"></option>
    <option value="ໂຮງງານຜະລິດເຂົ້າແຫ້ງ"></option>
    <option value="ໂຮງງານເສັ້ນດ້າຍ-ເກີບໜັງ"></option>
    <option value="ກອງພັນກໍ່ສ້າງຂົວ-ທາງ 587"></option>
    <option value="ກອງພັນກໍ່ສ້າງເຄຫາ 511"></option>
    <option value="ກອງພັນເກັບກູ້ລະເບີດ 579"></option>
    <option value="ໂຮງຮຽນຂັບລົດ404"></option>
    <option value="ສູນເສຍອົງຄະພິເສດ790"></option>
    <option value="ສາງອາໄຫຼ່ ວໍ 1"></option>
    <option value="ກົມທະຫານອາກາດ"></option>
    <option value="ກົມທະຫານອາກາດ"></option>
    <option value="ສູນ 14"></option>
    <option value="ກອງພັນ 403"></option>
    <option value="ສູນບັນຊາ 761"></option>
    <option value="ກອງບັນຊາການທະຫານອາກາດ"></option>
    <option value="ໂຮງສີບຸນຍົມ"></option>
    <option value="ນະໂຍບາຍ"></option>
    <option value="ໂຮງໝໍຄັງວຽງ119"></option>
    <option value="ພະນັກງານບໍານານ"></option>
    <option value="ສູນບັນຊາ"></option>
    <option value="ກົມປ້ອງກັນພາຍໃນ"></option>
    <option value="ໂຮງສີສີໄຄ"></option>
    <option value="ໂຮງສີບົວໄຂ"></option>
</datalist>

<datalist id="contents">
    <option value="ຂໍເຄື່ອງປະຈຳປີ"></option>
    <option value="ຂໍເຄື່ອງທະຫານໃໝ່"></option>
    <option value="ຂໍເຄື່ອງເລື່ອນຊັ້ນ"></option>
    <option value="ຂໍເຄື່ອງເພີ່ມວິຊາສະເພາະ"></option>
    <option value="ຂໍເຄື່ອງເພີ່ມສະໜາມ"></option>
    <option value="ຂໍເຄື່ອງຍາວນານ"></option>
    <option value="ຂໍເຄື່ອງພະນັກງານເສຍອົງຄະ"></option>
    <option value="ຂໍເຄື່ອງປະດັບຊັ້ນ"></option>
</datalist>

<datalist id="signs">
    <option value="ພົຈ ບຸນແຍງ ວິໄລສົມ"></option>
    <option value="ພັອ ໝອນແກ້ວ ຄຳອ້ວນ"></option>
    <option value="ພັອ ປອ ສົມພິນ ພົມມະຈັນ"></option>
</datalist>